# Netlify configuration for Baby Name Swiper App
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyCCfgvBHss14O0YtZ0G3e_dCRo-WYmkR1I"
  VITE_FIREBASE_AUTH_DOMAIN = "baby-name-swiper.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "baby-name-swiper"
  VITE_FIREBASE_STORAGE_BUCKET = "baby-name-swiper.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "926332937942"
  VITE_FIREBASE_APP_ID = "1:926332937942:web:f3f481fdce27436cc34b77"
  VITE_FIREBASE_MEASUREMENT_ID = ""

[dev]
  command = "vite"
  port = 5000
  publish = "dist"
